### ISSUE TITLE
Code Visualization

### ISSUE THREAD

**Issue by cherishdd** [ekincanufuktepe/fun_stuff#1]
Hello, sorry to bother you in this project, is it convenient to share the codes of these two graphs? Thank you very much！
![image](https://user-images.githubusercontent.com/39721645/235135719-1092a180-a2ad-4c0a-8b32-f2fe598e2e84.png)

**Comment by ekincanufuktepe** [comment]
Hi @cherishdd, I am closing this issue because it is not related to this repo.
